// Bastion Protocol — typed asset manifest.
//
// The manifest JSON (generated by scripts/gen-assets.mjs) is the single source
// of truth mapping logical asset names to file paths, frame configs, 9-slice
// insets, and per-Charge placeholder colors. It is imported (bundled + typed)
// here; the actual asset *files* live under public/ and load at runtime.

import manifestJson from "../../../public/data/asset-manifest.json";

export interface PlaceholderSpec {
  color: string;
  label: string;
}

export interface AnimSpec {
  start: number;
  end: number;
  frameRate: number;
  repeat: number;
}

export interface ImageAsset {
  type: "image";
  path: string;
  width: number;
  height: number;
  placeholder: PlaceholderSpec;
}

export interface SheetAsset {
  type: "spritesheet";
  path: string;
  frameWidth: number;
  frameHeight: number;
  frameCount: number;
  anims: Record<string, AnimSpec>;
  placeholder: PlaceholderSpec;
}

export interface PanelSlice {
  left: number;
  right: number;
  top: number;
  bottom: number;
}

export interface PanelAsset {
  type: "panel";
  path: string;
  width: number;
  height: number;
  slice: PanelSlice;
  placeholder: PlaceholderSpec;
}

export interface AudioAsset {
  type: "audio";
  path: string;
  stream: boolean;
  fallback: "synth" | "none";
}

export type AssetEntry = ImageAsset | SheetAsset | PanelAsset | AudioAsset;

export interface AssetManifest {
  version: number;
  assets: Record<string, AssetEntry>;
}

export const MANIFEST = manifestJson as unknown as AssetManifest;
export const ASSETS = MANIFEST.assets;

export function entriesOfType<T extends AssetEntry["type"]>(
  type: T,
): [string, Extract<AssetEntry, { type: T }>][] {
  return Object.entries(ASSETS).filter(([, a]) => a.type === type) as [
    string,
    Extract<AssetEntry, { type: T }>,
  ][];
}

export function getEntry(key: string): AssetEntry | undefined {
  return ASSETS[key];
}

/** Anim key namespacing so two sheets can share an anim name (e.g. "walk"). */
export function animKey(assetKey: string, anim: string): string {
  return `${assetKey}:${anim}`;
}

// --- Convenience key builders (keep call sites free of string literals) ------
export const AssetKeys = {
  enemy: (kind: string) => `enemy.${kind.toLowerCase()}`,
  tileset: (strongholdId: string) => `tileset.${strongholdId}`,
  bgSky: (strongholdId: string) => `bg.${strongholdId}.sky`,
  bgMid: (strongholdId: string) => `bg.${strongholdId}.mid`,
  projectile: (charge: string) => `projectile.${charge.toLowerCase()}`,
  chargeIcon: (charge: string) => `icon.charge.${charge.toLowerCase()}`,
  abilityIcon: (ability: string) => `icon.ability.${ability.toLowerCase()}`,
  music: (state: string) => `audio.music.${state}`,
  shot: (charge: string) => `audio.sfx.shot.${charge.toLowerCase()}`,
} as const;
